'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_BrokerRiskCounter

    '''<summary>
    '''rbSummary_Low control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSummary_Low As Global.Telerik.Web.UI.RadPushButton

    '''<summary>
    '''RadToolTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip1 As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''rbSummary_Med control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSummary_Med As Global.Telerik.Web.UI.RadPushButton

    '''<summary>
    '''RadToolTip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip2 As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''rbSummary_High control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSummary_High As Global.Telerik.Web.UI.RadPushButton

    '''<summary>
    '''RadToolTip3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip3 As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''rgvFiltered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgvFiltered As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''panel_Options control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_Options As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rlbAssignRisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbAssignRisk As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''reSearchNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reSearchNotes As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''reOfficeNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reOfficeNotes As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''hfRiskFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRiskFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sqlRiskFiltered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlRiskFiltered As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''notice_Popup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notice_Popup As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''window_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_alert As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''window_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_form As Global.Telerik.Web.UI.RadWindow
End Class
