'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wz_885326974

    '''<summary>
    '''hfFormHash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormHash As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFormId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIsValidated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIsValidated As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfInvalidList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfInvalidList As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rwIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwIdentification As Global.Telerik.Web.UI.RadWizard

    '''<summary>
    '''step_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_Verification As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter1 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''navigationPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navigationPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''asyncNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncNewDocument As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''RadButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''txtp_streetnum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_streetnum As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_street As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_unitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_unitNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_city As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_zipcode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtpropAddrLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpropAddrLine2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rddClientSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rddClientSource As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''txtClientSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientSource As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgent As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBroker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBroker As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdpVerifiedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpVerifiedDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txttodaysDated1_yyyy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_yyyy As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_mmmm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_mmmm As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_d As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadSplitbar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitbar1 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''EndPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone1 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane1 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''uc_step_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_step_Verification As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_HeaderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_HeaderInfo As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter2 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane1 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''txtindividualName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtindividualAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rcbEmployment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbEmployment As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtnatureOfBusinessOccupation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnatureOfBusinessOccupation As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessLocation As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rbGovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGovernmentId As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rcbShowAllSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbShowAllSteps As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''rbCreditMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCreditMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbDualIdMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDualIdMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbUnidentified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbUnidentified As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadSplitbar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitbar2 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane9 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone2 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane2 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_HeaderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_HeaderInfo As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_GovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_GovernmentId As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter3 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane2 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''txtidDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidDocument As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtdocIdentifierNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdocIdentifierNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingJurisdiction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingJurisdiction As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDocExpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocExpDate As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''rcbRemoteIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbRemoteIdentification As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rbList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbList As Global.Telerik.Web.UI.RadRadioButtonList

    '''<summary>
    '''asyncRemoteId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncRemoteId As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''RadSplitbar5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitbar5 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane10 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone3 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane3 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_GovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_GovernmentId As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_CreditFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_CreditFile As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter4 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane3 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSplitbar7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitbar7 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane11 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone4 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane4 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_CreditFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_CreditFile As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_DualId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_DualId As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter5 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane4 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''chkOpt_dualID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_dualID1 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_dualID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_dualID2 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_dualID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_dualID3 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtacctType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacctType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadSplitBar10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar10 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane12 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone5 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane5 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_DualId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_DualId As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_UnrepresentedParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_UnrepresentedParty As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter6 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane5 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSplitBar12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar12 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane13 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone6 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane6 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_UnrepresentedParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_UnrepresentedParty As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_ThirdParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_ThirdParty As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter7 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane6 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rrbTransConductedBehalfClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rrbTransConductedBehalfClient As Global.Telerik.Web.UI.RadRadioButtonList

    '''<summary>
    '''chkOpt_transConductedBehalfClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_transConductedBehalfClient As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtReasonActingOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonActingOn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''panel_ThirdParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_ThirdParty As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtthirdPartyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtthirdPartyBusinessOccupation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyBusinessOccupation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox5 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox6 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadSplitBar14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar14 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane14 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone7 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane7 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_ThirdParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_ThirdParty As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_Relationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_Relationship As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter10 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane17 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox4 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox7 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadSplitBar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar4 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RadPane18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane18 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone10 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane10 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_Relationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_Relationship As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''step_WrapUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_WrapUp As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadSplitter9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter9 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane8 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rlWrapUpMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlWrapUpMessage As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''rtbFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbFileName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rbSaveForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSaveForm As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbReviewDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbReviewDoc As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbSubmitToOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSubmitToOffice As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rcbSendSelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbSendSelf As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadPane15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane15 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadSlidingZone8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingZone8 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''RadSlidingPane8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSlidingPane8 As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''Uc_step_WrapUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uc_step_WrapUp As Global.SmartForms.uc_ComplianceNotes

    '''<summary>
    '''rtbText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbText As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSendText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSendText As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSendEmail As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''window_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_alert As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''window_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_form As Global.Telerik.Web.UI.RadWindow
End Class
