'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wz_885326974

    '''<summary>
    '''hfFormHash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormHash As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFormId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''butSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butSendOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSendOffice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rcbWhatForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbWhatForm As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''asyncNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncNewDocument As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''RadButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rwIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwIdentification As Global.Telerik.Web.UI.RadWizard

    '''<summary>
    '''step_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_Verification As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtp_streetnum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_streetnum As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_street As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_unitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_unitNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_city As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_zipcode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtpropAddrLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpropAddrLine2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgent As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBroker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBroker As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_yyyy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_yyyy As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_mmmm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_mmmm As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_d As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdpVerifiedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpVerifiedDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''step_HeaderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_HeaderInfo As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtindividualName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtindividualAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rbGovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGovernmentId As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rcbShowAllSteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbShowAllSteps As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''rbCreditMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCreditMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbDualIdMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDualIdMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbUnidentified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbUnidentified As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''step_GovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_GovernmentId As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtidDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidDocument As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtdocIdentifierNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdocIdentifierNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingJurisdiction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingJurisdiction As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDocExpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocExpDate As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''rcbRemoteIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbRemoteIdentification As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rbList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbList As Global.Telerik.Web.UI.RadRadioButtonList

    '''<summary>
    '''asyncRemoteId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncRemoteId As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''step_CreditFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_CreditFile As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''step_DualId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_DualId As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''step_UnrepresentedParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_UnrepresentedParty As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''step_ThirdParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_ThirdParty As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''rrbTransConductedBehalfClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rrbTransConductedBehalfClient As Global.Telerik.Web.UI.RadRadioButtonList

    '''<summary>
    '''txtReasonActingOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonActingOn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''step_ThirdPartIdent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_ThirdPartIdent As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtthirdPartyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtthirdPartyBusinessOccupation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyBusinessOccupation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox5 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox6 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''step_WrapUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_WrapUp As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''rbReviewDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbReviewDoc As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rtbText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbText As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSendText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSendText As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSendEmail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''window_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_alert As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''window_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_form As Global.Telerik.Web.UI.RadWindow
End Class
