'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wz_885326974

    '''<summary>
    '''hfFormHash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormHash As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFormId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''butSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butSendOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSendOffice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rcbWhatForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbWhatForm As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbShowMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbShowMobile As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''panelMobileIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMobileIdentity As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rtbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtbPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSendText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSendText As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''asyncNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncNewDocument As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''RadButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rwIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwIdentification As Global.Telerik.Web.UI.RadWizard

    '''<summary>
    '''step_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step_Verification As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtp_streetnum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_streetnum As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_street As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_unitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_unitNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_city As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtp_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtp_zipcode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtpropAddrLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpropAddrLine2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgent As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBroker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBroker As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_yyyy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_yyyy As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_mmmm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_mmmm As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txttodaysDated1_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttodaysDated1_d As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdpVerifiedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpVerifiedDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadWizardStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWizardStep2 As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtindividualName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtindividualAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtindividualAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtindividualAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rbGovernmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGovernmentId As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbCreditMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCreditMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbDualIdMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDualIdMethod As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rbUnidentified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbUnidentified As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWizardStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWizardStep3 As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''RadWizardStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWizardStep4 As Global.Telerik.Web.UI.RadWizardStep

    '''<summary>
    '''txtnatureOfBusinessOccupation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnatureOfBusinessOccupation As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtidDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidDocument As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtdocIdentifierNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdocIdentifierNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingJurisdiction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingJurisdiction As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtissuingCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissuingCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDocExpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocExpDate As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtcreditBureau1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcreditBureau1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtcreditBureau2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcreditBureau2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtcreditBureauRefNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcreditBureauRefNum As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_dualID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_dualID2 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_dualID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_dualID3 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''checkboxhold3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkboxhold3 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtsourceName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourceName3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtacctType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacctType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBillNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNumber3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_ascertainIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_ascertainIdentity As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''chkOpt_reasonsMeasuresUnsccessful control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_reasonsMeasuresUnsccessful As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtascertainIdentityExplain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtascertainIdentityExplain1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtascertainIdentityExplain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtascertainIdentityExplain2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdpascertainIdentityDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpascertainIdentityDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadCheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox1 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox2 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkOpt_transConductedBehalfClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpt_transConductedBehalfClient As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox9 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtreasonsMeasuresUnsuccessful1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreasonsMeasuresUnsuccessful1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtreasonsMeasuresUnsuccessful2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreasonsMeasuresUnsuccessful2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyDOB As Global.Telerik.Web.UI.RadDateInput

    '''<summary>
    '''txtthirdPartyBusinessOccupation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyBusinessOccupation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyBusinessOccupation2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyIncorporationNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyIncorporationNumber2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCheckBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox7 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox10 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox11 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox12 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox8 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtlowRiskExplain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlowRiskExplain As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCheckBox17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox17 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtmedRiskExplain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmedRiskExplain As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCheckBox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox16 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox18 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txthighRiskExplain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthighRiskExplain As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCheckBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox13 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox14 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox15 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox19 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''RadCheckBox20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox20 As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''txtD1explain19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtD1explain19 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyReasonsMeasuresTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyReasonsMeasuresTaken As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtthirdPartyReasonsMeasuresTaken2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtthirdPartyReasonsMeasuresTaken2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''window_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_alert As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''window_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents window_form As Global.Telerik.Web.UI.RadWindow
End Class
