'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FintracForms

    '''<summary>
    '''RadAsyncUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAsyncUpload1 As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''rtbFileTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbFileTitle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtbAgentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbAgentName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rbLoadPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLoadPdf As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadPdfViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPdfViewer1 As Global.Telerik.Web.UI.RadPdfViewer
End Class
