'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PDFDataFieldMapper

    '''<summary>
    '''hfSeller1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSeller1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSeller2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSeller2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSeller3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSeller3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lbShowPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShowPanel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbTestCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTestCode As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_topbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_topbar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rcbFintracForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFintracForm As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lbViewFintrac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbViewFintrac As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rcbResetFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbResetFields As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''panelUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelUpload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''asyncNewDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asyncNewDocument As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''rbRightLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbRightLoad As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rcbRightPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbRightPaging As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''rlFileUploaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlFileUploaded As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''lbResetUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbResetUpload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rgvLeftSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgvLeftSide As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rtbSearchString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbSearchString As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbForceSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbForceSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rgvRightSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgvRightSide As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''sqlFintracForms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFintracForms As Global.System.Web.UI.WebControls.SqlDataSource
End Class
