'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PropertyFintrac

    '''<summary>
    '''panelNewCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelNewCard As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rcbForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbForm As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rtbMLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbMLS As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbSearchDDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSearchDDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rtbPropertyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbPropertyAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtbFileTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbFileTitle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtbAgentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbAgentName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbNewRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNewRecord As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rgFieldList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgFieldList As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''sqlFieldDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFieldDataList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RadPdfViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPdfViewer1 As Global.Telerik.Web.UI.RadPdfViewer
End Class
